version: '3'

services:
  greentube:
    image: greentube_app:Build26
    ports: 
      - 8080
    environment:
      - SERVICE_PORTS=8080
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 30s
    networks:
      - web

  proxy:
    image: dockercloud/haproxy
    depends_on:
      - greentube
    environment:
      - BALANCE=leastconn
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    networks:
      - web
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  web:
    driver: overlay 
